version: "3.7"
services:
  service:
    container_name: user-service
    image: nginx:latest
    ports:
      - "9000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - api
    restart: unless-stopped

  api:
    container_name: user-api
    image: python:3
    command:
      - /bin/sh
      - -c
      - | 
        cd /usr/src/
        pip install --upgrade pip
        pip install -r requirements.txt
        gunicorn --workers=3 user_service.wsgi:application --bind 0.0.0.0:8000 --env DJANGO_SETTINGS_MODULE=user_service.settings --reload
    volumes:
      - ../:/usr/src/
    depends_on:
      - mysql
    expose:
      - "8000"

  mysql:
    container_name: user-db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=<DB_PASSWORD>
      - MYSQL_DATABASE=user_service
    volumes:
      - ./mysql/default.cnf:/etc/mysql/conf.d/default.cnf

networks:
  default_bridge:
    ipam:
      driver: default
      config:
        - subnet: "172.30.0.0/16"