name:  user-service-ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create Secret
      run: |
        cat <<EOF > ${{ github.workspace }}/secrets.json
        {
            "PYTHON_SECRET_KEY": "${{ secrets.PYTHON_SECRET_KEY }}",
            "AWS_ACCESS_KEY_ID": "${{ secrets.AWS_ACCESS_KEY_ID }}",
            "AWS_SECRET_ACCESS_KEY": "${{ secrets.AWS_ACCESS_KEY_ID }}",
            "AWS_REGION": "${{ secrets.AWS_REGION }}",
            
            "DB_USER": "root",
            "DB_PASSWORD": "${{ secrets.DB_PASSWORD }}",
            "DB_HOST": "127.0.0.1",
            "DB_PORT": "3306"
        }
        EOF
    - name: Run Mysql Container
      uses: addnab/docker-run-action@v3
      with:
        image: mysql:5.7
        options: -v ${{ github.workspace }}/docker/mysql/default.cnf:/etc/mysql/conf.d/default.cnf -e MYSQL_ROOT_PASSWORD=2345678 -e MYSQL_DATABASE=user_service -p 3306:3306
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test